In [96]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [97]:
dataset=pd.read_excel(r'C:\Users\user\Accident_data\Acc_data_version2 - Copy.xlsx')

In [77]:
pwd

'C:\\Users\\user\\Accident_data'

In [98]:
dataset.head()


State  Accidents risk        Day  Day risk scale         Time  \
0  Andhra Pradesh             3.5     Monday             3.5  6am to 10pm   
1  Andhra Pradesh             3.5    Tuesday             2.0  10am to 8pm   
2  Andhra Pradesh             3.5  Wednesday             2.0  10pm to 8am   
3  Andhra Pradesh             3.5   Thursday             2.0  6am to 10pm   
4  Andhra Pradesh             3.5     Friday             3.0  10am to 8pm   

   Time risk scale Weather  Weather risk scale       Age  Age risk scale  ...  \
0              3.5   Foggy                 4.0     18-25             5.0  ...   
1              2.5   Rainy                 3.5     25-35             3.5  ...   
2              5.0   Sunny                 2.0     35-55             3.0  ...   
3              3.5   Foggy                 4.0  Above 55             2.5  ...   
4              2.5   Rainy                 3.5     18-25             5.0  ...   

  Cost % Of Commodity Damage          Packed_in  \
0                        0.7  Cardboard_Packing   
1                        0.7    Plastic_Packing   
2                        0.2    Plastic_Packing   
3                        0.7  Cardboard_Packing   
4                        0.4  Cardboard_Packing   

                           VEHICLE_TYPE  WEIGHT_CAPACITY(METRIC_TON)  \
0  Light COMMERCIAL Vehicles (TATA ACE)                          1.5   
1                             14 FT DCM                          5.0   
2                             17 FT DCM                          5.5   
3                             19 FT DCM                          7.5   
4                18 FT Lorry - 6 WHEELS                          9.0   

  COMMODITY WEIGHT   OVERLOAD  OVERLOAD SCALE  VEHICLE_HEALTH  \
0              2.0  33.333333               6             Bad   
1              4.0 -20.000000               1          Medium   
2              5.0  -9.090909               1            Good   
3              7.0  -6.666667               1             Bad   
4              8.0 -11.111111               1          Medium   

   VEHICLE HEALTH SCALE  ACCIDENT RISK PERCENTAGE  
0                     9                    50.000  
1                     5                    28.750  
2                     3                    28.125  
3                     9                    45.000  
4                     5                    33.125  

[5 rows x 23 columns]

In [99]:
dataset=dataset.drop(["State","Day","Time","Weather","Age","Vehicle_Age","COMMODITY","Cost % Of Commodity Damage","Packed_in","VEHICLE_TYPE","WEIGHT_CAPACITY(METRIC_TON)","COMMODITY WEIGHT","VEHICLE_HEALTH"],axis=1)

In [82]:
dataset

Accidents risk  Day risk scale  Time risk scale  Weather risk scale  \
0                3.5             3.5              3.5                 4.0   
1                3.5             2.0              2.5                 3.5   
2                3.5             2.0              5.0                 2.0   
3                3.5             2.0              3.5                 4.0   
4                3.5             3.0              2.5                 3.5   
5                3.5             3.5              5.0                 2.0   
6                3.5             3.5              3.5                 4.0   
7                3.5             3.5              2.5                 3.5   
8                3.5             2.0              5.0                 2.0   
9                3.5             2.0              3.5                 4.0   
10               3.5             2.0              2.5                 3.5   
11               3.5             3.0              5.0                 2.0   
12               3.5             3.5              3.5                 4.0   
13               3.5             3.5              2.5                 3.5   
14               3.5             3.5              5.0                 2.0   
15               3.5             2.0              3.5                 4.0   
16               3.5             2.0              2.5                 3.5   
17               3.5             2.0              5.0                 2.0   
18               3.5             3.0              3.5                 4.0   
19               3.5             3.5              2.5                 3.5   
20               3.5             3.5              5.0                 2.0   
21               3.5             3.5              3.5                 4.0   
22               3.5             2.0              2.5                 3.5   
23               2.0             2.0              5.0                 2.0   
24               2.0             2.0              3.5                 4.0   
25               2.0             3.0              2.5                 3.5   
26               2.0             3.5              5.0                 2.0   
27               2.0             3.5              3.5                 4.0   
28               2.0             3.5              2.5                 3.5   
29               2.0             2.0              5.0                 2.0   
...              ...             ...              ...                 ...   
1307             2.5             3.5              2.5                 4.5   
1308             5.0             3.5              3.5                 5.0   
1309             5.0             3.5              2.5                 5.0   
1310             5.0             3.5              5.0                 4.0   
1311             5.0             2.0              3.5                 5.0   
1312             5.0             2.0              2.5                 5.0   
1313             5.0             2.0              5.0                 4.5   
1314             5.0             3.0              3.5                 4.0   
1315             4.5             2.0              2.5                 4.0   
1316             4.5             3.0              5.0                 5.0   
1317             4.5             3.5              3.5                 4.0   
1318             4.5             3.5              2.5                 4.5   
1319             4.5             3.5              5.0                 5.0   
1320             4.5             2.0              3.5                 4.0   
1321             4.5             2.0              2.5                 4.5   
1322             3.0             2.0              2.5                 4.0   
1323             3.0             3.0              5.0                 5.0   
1324             3.0             3.5              3.5                 5.0   
1325             3.0             3.5              2.5                 5.0   
1326             3.0             3.5              5.0                 4.0   
13

In [100]:
dataset=dataset.drop('OVERLOAD',axis=1)

In [101]:
X=pd.DataFrame(dataset.iloc[:,:-1])
y=pd.DataFrame(dataset.iloc[:,-1])

In [9]:
type(X)

pandas.core.frame.DataFrame

In [10]:
type(y)

pandas.core.frame.DataFrame

In [11]:
type(X_train)

NameError: name 'X_train' is not defined

In [ ]:
type(y_train)

In [102]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1336 entries, 0 to 1335
Data columns (total 9 columns):
Accidents risk              1336 non-null float64
Day risk scale              1336 non-null float64
Time risk scale             1336 non-null float64
Weather risk scale          1336 non-null float64
Age risk scale              1336 non-null float64
Vehicle Age risk scale      1336 non-null float64
OVERLOAD SCALE              1336 non-null int64
VEHICLE HEALTH SCALE        1336 non-null int64
ACCIDENT RISK PERCENTAGE    1336 non-null float64
dtypes: float64(7), int64(2)
memory usage: 94.0 KB


In [104]:
dataset['OVERLOAD SCALE'] = dataset['OVERLOAD SCALE'].astype(float)

In [105]:
dataset['VEHICLE HEALTH SCALE'] = dataset['VEHICLE HEALTH SCALE'].astype(float)

In [106]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1336 entries, 0 to 1335
Data columns (total 9 columns):
Accidents risk              1336 non-null float64
Day risk scale              1336 non-null float64
Time risk scale             1336 non-null float64
Weather risk scale          1336 non-null float64
Age risk scale              1336 non-null float64
Vehicle Age risk scale      1336 non-null float64
OVERLOAD SCALE              1336 non-null float64
VEHICLE HEALTH SCALE        1336 non-null float64
ACCIDENT RISK PERCENTAGE    1336 non-null float64
dtypes: float64(9)
memory usage: 94.0 KB


In [84]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [68]:
X_test=X.iloc[1336:]

In [69]:
X_test

Accidents risk  Day risk scale  Time risk scale  Weather risk scale  \
1336             4.5             4.0              3.0                 4.0   

      Age risk scale  Vehicle Age risk scale  OVERLOAD  OVERLOAD SCALE  \
1336             4.0                     4.0       4.0               1   

      VEHICLE HEALTH SCALE  
1336                     5

In [85]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(min_samples_split=4,max_depth=25)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(criterion='mse', max_depth=25, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=4, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [86]:
y_pred = regressor.predict(X_test)

In [87]:
y_pred[30:35]

array([36.875     , 28.125     , 29.375     , 34.85714286, 30.        ])

In [88]:
y_test[30:35]

ACCIDENT RISK PERCENTAGE
54                      36.875
950                     28.125
1088                    29.375
45                      33.750
988                     30.000

In [36]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [37]:
y_pred = regressor.predict(X_test)

In [38]:
y_pred[30:35]

array([[38.79853623],
       [27.26065976],
       [28.92546799],
       [36.92896295],
       [30.26894712]])

In [39]:
y_test[30:35]

ACCIDENT RISK PERCENTAGE
54                      36.875
950                     28.125
1088                    29.375
45                      33.750
988                     30.000

In [40]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 1.8537386698289815
Mean Squared Error: 12.072135806241691
Root Mean Squared Error: 3.4744979214617024


In [42]:
import pickle 
  
# Save the trained model as a pickle string. 
model= pickle.dumps(regressor)

In [43]:
regressor_from_pickle = pickle.loads(model)

In [44]:
regressor_from_pickle.predict(X_test)

array([[32.23720913],
       [38.24400031],
       [37.82728352],
       [28.06541123],
       [37.78924736],
       [29.95504773],
       [37.07153577],
       [33.45020749],
       [31.13618469],
       [26.77513836],
       [47.52654389],
       [31.50116584],
       [27.68647111],
       [46.42409388],
       [33.69048785],
       [37.85112137],
       [27.31233497],
       [36.96015792],
       [39.81849382],
       [37.26506317],
       [29.03635983],
       [31.32591201],
       [36.95430886],
       [27.66619511],
       [31.79221115],
       [28.95909698],
       [30.76202862],
       [30.42817145],
       [29.00786297],
       [40.87227956],
       [38.79853623],
       [27.26065976],
       [28.92546799],
       [36.92896295],
       [30.26894712],
       [36.58847665],
       [31.79390064],
       [29.32367686],
       [26.36805429],
       [38.16796257],
       [54.17818148],
       [40.42033321],
       [29.24536214],
       [29.4443652 ],
       [27.58700569],
       [26

In [89]:
from sklearn.externals import joblib

In [48]:
import urllib.request
import json

In [91]:
from sklearn.externals import joblib 
  
# Save the model as a pickle in a file 
joblib.dump(regressor, 'Accident.pkl') 
  
# Load the model from the file 
knn_from_joblib = joblib.load('Accident.pkl')  
  
# Use the loaded model to make predictions 
knn_from_joblib.predict(X_test) 

array([32.5       , 37.36607143, 35.        , 30.625     , 43.75      ,
       30.        , 34.375     , 31.875     , 30.875     , 27.5       ,
       46.66666667, 30.875     , 28.125     , 55.        , 31.25      ,
       37.5       , 27.5       , 34.85714286, 35.        , 35.        ,
       30.625     , 31.25      , 34.85714286, 28.125     , 31.875     ,
       29.375     , 27.70833333, 30.        , 29.58333333, 49.5       ,
       36.875     , 28.125     , 29.375     , 34.85714286, 30.        ,
       35.625     , 31.875     , 29.375     , 26.25      , 37.36607143,
       61.875     , 38.33333333, 30.        , 30.        , 27.5       ,
       28.125     , 37.59375   , 38.75      , 38.125     , 28.75      ,
       34.16666667, 26.25      , 50.        , 32.8125    , 27.5       ,
       37.5       , 30.625     , 26.25      , 29.375     , 25.625     ,
       36.5625    , 36.91666667, 28.75      , 33.125     , 29.375     ,
       37.36607143, 32.91666667, 29.375     , 32.5       , 28.75

In [73]:
clf.predict(X_test) 

array([36.5625])

In [47]:
model.dump(regressor,'Acc_Data1.pkl') 

AttributeError: 'bytes' object has no attribute 'dump'

In [70]:
regressor_from_joblib = joblib.load('model.pkl')  
  
# Use the loaded model to make predictions 
regressor_from_joblib.predict(X_test) 

FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'

In [213]:
pwd

'C:\\Users\\user\\Accident_data'

In [60]:
import _pickle as pickle

pickle_file = open('filename.pkl')
data = pickle.load(pickle_file)

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 46: character maps to <undefined>

In [71]:
clf = joblib.load('Accident.pkl')

In [62]:
clf

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [64]:
import pandas as pd
from flask import Flask, jsonify, request
import pickle

In [55]:
# load model
with open('clf','rb') as f:
    mp=pickle.load(f)

UnpicklingError: invalid load key, '\x15'.

In [57]:
with open('Accident.pkl','wb') as fout:
    pickle.dump([1,2,3],fout)

# read data from a file
with open('Accident.pkl') as fin:
    print(pickle.load(fin))

TypeError: a bytes-like object is required, not 'str'

In [67]:
export FLASK_ENV=development
flask run

SyntaxError: invalid syntax (<ipython-input-67-d63b1d43e7a3>, line 1)

In [65]:


# load model

# app
app = Flask(__name__)

# routes
@app.route('/', methods=['POST'])

def predict():
    # get data
    data = request.get_json(force=True)

    # convert data into dataframe
    data.update((x, [y]) for x, y in data.items())
    data_df = pd.DataFrame.from_dict(data)

    # predictions
    result = clf.predict(data_df)

    # send back to browser
    output = {'results': int(result[0])}

    # return data
    return jsonify(results=output)

if __name__ == '__main__':
    app.run(port = 5000, debug=True)

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: on


 * Restarting with stat


SystemExit: 1

C:\Users\user\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3333: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [66]:
%tb

SystemExit: 1

In [92]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle 
from flask import Flask, jsonify, request
import pickle
import joblib 
dataset=pd.read_excel(r'C:\Users\user\Accident_data\Acc_data_version2 - Copy.xlsx')
dataset=dataset.drop(["State","Day","Time","Weather","Age","OVERLOAD","Vehicle_Age","COMMODITY","Cost % Of Commodity Damage","Packed_in","VEHICLE_TYPE","WEIGHT_CAPACITY(METRIC_TON)","COMMODITY WEIGHT","VEHICLE_HEALTH"],axis=1)
X=pd.DataFrame(dataset.iloc[:,:-1])
y=pd.DataFrame(dataset.iloc[:,-1])
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(min_samples_split=4,max_depth=25)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)


In [93]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1337 entries, 0 to 1336
Data columns (total 9 columns):
Accidents risk              1337 non-null float64
Day risk scale              1337 non-null float64
Time risk scale             1337 non-null float64
Weather risk scale          1337 non-null float64
Age risk scale              1337 non-null float64
Vehicle Age risk scale      1337 non-null float64
OVERLOAD SCALE              1337 non-null int64
VEHICLE HEALTH SCALE        1337 non-null int64
ACCIDENT RISK PERCENTAGE    1337 non-null float64
dtypes: float64(7), int64(2)
memory usage: 94.1 KB


In [95]:
dataset['Accidents risk'][0]

3.5